### ISSUE TITLE
ImportError: cannot import name 'bytes_type

### ISSUE THREAD

**Issue by larminen** [lepture/flask-oauthlib#391]
I think the latest changes in authlib [1] break flask-oauthlib. [2]

I understand that this project is not maintained anymore but AirFlow still unfortunately uses this instead of authlib. [3] 

[1] https://github.com/oauthlib/oauthlib/commit/8aa89569f14b493ba2672d7a64c7c1c138c82c3b#diff-6315ddc4d1c3711d8b60d005b775c375 
[2] https://github.com/lepture/flask-oauthlib/blob/9e6f152a5bb360e7496210da21561c3e6d41b0e1/flask_oauthlib/utils.py#L5
[3] https://issues.apache.org/jira/browse/AIRFLOW-3753?jql=text%20~%20%22flask_oauthlib%22

**Comment by jlfsdtc** [comment]
i have this error too

**Comment by jlfsdtc** [comment]
> i have this error too

add "requests-oauthlib==1.1.0" to requirements.txt can fix it #390

**Comment by larminen** [comment]
Good to also pin oauthlib to version < 3.0 (like suggested in the linked Issue)

**Comment by lepture** [comment]
It is fixed in master. You can always pin your dependencies in requirements.txt

**Comment by brubakerjeff** [comment]
Were there other changes related to this? Working on a fork a fork of gae-init and still getting this error..


INFO     2019-03-10 19:08:09,359 module.py:861] default: "GET /_ah/warmup HTTP/1.1" 500 4511
  File "/mnt/c/Users/bruba/Desktop/cloudpayback/main/auth/__init__.py", line 3, in <module>
    from .auth import *
  File "/mnt/c/Users/bruba/Desktop/cloudpayback/main/auth/auth.py", line 8, in <module>
    from flask_oauthlib import client as oauth
  File "lib/flask_oauthlib/client.py", line 20, in <module>
    from .utils import to_bytes
  File "lib/flask_oauthlib/utils.py", line 5, in <module>
    from oauthlib.common import to_unicode, bytes_type

  oauthlib==2.1.0
  requests-oauthlib==1.1.0

https://gist.github.com/brubakerjeff/47d1f10264ec05ae42e22173d3692992

**Comment by brubakerjeff** [comment]
Digging deeper, was bytes_type removed from 

oauthlib.common?

Old version
https://github.com/oauthlib/oauthlib/blob/32e5ad1509a8d46fa402776f54fbabef4b1ded63/oauthlib/common.py#L52

New versino
https://github.com/oauthlib/oauthlib/blob/ff108214eeb8c5f996cff90b469344cfd8a9f5a7/oauthlib/common.py#L56

Next breadcrumb/thought, is bytes_type needed in utils.py?

**Comment by brubakerjeff** [comment]
Digging deeper looks like a python2/python3 issue.

Google still has Google App Engine pegged for python2.7 so I'm thinking adding this logic to flash-oauthlib is best approach. I can try more later.

PY3 = sys.version_info[0] == 3

if PY3:
    unicode_type = str
    bytes_type = bytes
else:
    unicode_type = unicode
    bytes_type = str"

**Comment by ageis** [comment]
What's the fix for this (running on Python 3.7)?
